### ISSUE TITLE
Guide me to run this Application

### ISSUE THREAD

**Issue by Ezhil6999** [NonymousMorlock/ridy-admin-api#1]
I do no how to run this application can you help me with it

**Comment by NonymousMorlock** [comment]
It's unfortunately impossible, It's not my project; it's from https://github.com/Abdullah-129/RideFlutter, I was trying to revise it and use it, but it is locked behind a paywall unfortunately, if you check in the issues for that repo, you'll see where I asked him about it, he said you have to text him on instagram to pay for it, which I might do later when I need to use the project.
